/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.Locale;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author 0040481722011
 */
public class SupermercadoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SupermercadoJFrame
     */
    public SupermercadoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        mercadoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        itensLabel = new javax.swing.JLabel();
        qtdeitensLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        reaisLabel = new javax.swing.JLabel();
        produtoLabel = new javax.swing.JLabel();
        produtoTextField = new javax.swing.JTextField();
        vunitarioLabel = new javax.swing.JLabel();
        vunitTextField = new javax.swing.JTextField();
        qtdeLabel = new javax.swing.JLabel();
        qtdeTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        vrecebidoLabel = new javax.swing.JLabel();
        vrecebidoTextField = new javax.swing.JTextField();
        trocoLabel = new javax.swing.JLabel();
        trocoTextField = new javax.swing.JTextField();
        finalizarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para supermercado");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(241, 242, 246));

        jPanel4.setBackground(new java.awt.Color(52, 152, 219));

        mercadoLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        mercadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        mercadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mercadoLabel.setText("Mercadão");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mercadoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mercadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        produtosTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor Unitário (R$)", "Quantidade", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produtosTable.setFocusable(false);
        produtosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(produtosTable);

        jPanel2.setBackground(new java.awt.Color(230, 126, 34));

        itensLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        itensLabel.setForeground(new java.awt.Color(255, 255, 255));
        itensLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        itensLabel.setText("Itens");

        qtdeitensLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        qtdeitensLabel.setForeground(new java.awt.Color(255, 255, 255));
        qtdeitensLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        qtdeitensLabel.setText("0");

        subtotalLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        subtotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        subtotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subtotalLabel.setText("Subtotal");

        reaisLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        reaisLabel.setForeground(new java.awt.Color(255, 255, 255));
        reaisLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reaisLabel.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(qtdeitensLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reaisLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(itensLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subtotalLabel)))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itensLabel)
                    .addComponent(subtotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdeitensLabel)
                    .addComponent(reaisLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        produtoLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        produtoLabel.setText("Produto");

        produtoTextField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        produtoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                produtoTextFieldKeyPressed(evt);
            }
        });

        vunitarioLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        vunitarioLabel.setText("Valor Unitário (R$)");

        vunitTextField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        vunitTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vunitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vunitTextFieldActionPerformed(evt);
            }
        });
        vunitTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vunitTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vunitTextFieldKeyTyped(evt);
            }
        });

        qtdeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        qtdeLabel.setText("Quantidade");

        qtdeTextField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        qtdeTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtdeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdeTextFieldActionPerformed(evt);
            }
        });
        qtdeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtdeTextFieldKeyPressed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(68, 189, 50));
        addButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/add-24.png"))); // NOI18N
        addButton.setText("Adicionar");
        addButton.setBorder(null);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        xButton.setBackground(new java.awt.Color(232, 65, 24));
        xButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        xButton.setForeground(new java.awt.Color(255, 255, 255));
        xButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/delete-24.png"))); // NOI18N
        xButton.setText("Excluir");
        xButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(52, 152, 219));

        vrecebidoLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        vrecebidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        vrecebidoLabel.setText("Valor Recebido");

        vrecebidoTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        vrecebidoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vrecebidoTextFieldKeyPressed(evt);
            }
        });

        trocoLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        trocoLabel.setForeground(new java.awt.Color(255, 255, 255));
        trocoLabel.setText("Troco");

        trocoTextField.setEditable(false);
        trocoTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        finalizarButton.setBackground(new java.awt.Color(68, 189, 50));
        finalizarButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        finalizarButton.setForeground(new java.awt.Color(255, 255, 255));
        finalizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/ok-16_1.png"))); // NOI18N
        finalizarButton.setText("Finalizar");
        finalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setBackground(new java.awt.Color(232, 65, 24));
        cancelarButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/x-mark-4-16.png"))); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vrecebidoLabel)
                    .addComponent(vrecebidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(trocoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(trocoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrecebidoLabel)
                    .addComponent(trocoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(finalizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vrecebidoTextField)
                    .addComponent(trocoTextField))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produtoLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(produtoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(vunitarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(qtdeLabel))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(vunitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(qtdeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(produtoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produtoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtdeLabel)
                            .addComponent(vunitarioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtdeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vunitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:

        produtoTextField.setText("");
        vunitTextField.setText("");
        qtdeTextField.setText("");
        trocoTextField.setText("");
        qtdeitensLabel.setText("0");
        reaisLabel.setText("R$ 0.00");
        vrecebidoTextField.setText("");

        subtotal = 0.0;
        qtdedeitens = 0;

        DefaultTableModel modelo = (DefaultTableModel) produtosTable.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void finalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarButtonActionPerformed
        // TODO add your handling code here:

        if (vrecebidoTextField.getText().isEmpty()) {

            if (beep != null) {
                beep.run();
                JOptionPane.showMessageDialog(null, //NULL
                        "Favor inserir valor", // MENSAGEM
                        "Insira um valor", // TITULO
                        JOptionPane.WARNING_MESSAGE); //ICONE
            }
        } else {

            String vrecebido = vrecebidoTextField.getText();

            double a = Double.parseDouble(vrecebido.replace(",", ".").trim());

            troco = a - subtotal;

            trocoTextField.setText(String.valueOf(String.format("R$ %.2f ", troco)));

            int resposta = JOptionPane.showConfirmDialog(null, "Compra finalizada!\n"
                    + "Quantidade de itens comprados: " + qtdedeitens + "\n"
                    + "Troco: " + trocoTextField.getText() + "\n"
                    + "Deseja sair?",
                    "Fim",
                    JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_OPTION) {
                System.exit(0);
            } else {
                return;
            }

            produtoTextField.setText("");
            vunitTextField.setText("");
            qtdeTextField.setText("");
            vrecebidoTextField.setText("");
            trocoTextField.setText("");
            qtdeitensLabel.setText("0");
            reaisLabel.setText("R$ 0,00");
            subtotal = 0.0;
            qtdedeitens = 0;

            DefaultTableModel modelo = (DefaultTableModel) produtosTable.getModel();

            while (modelo.getRowCount() > 0) {
                modelo.removeRow(0);
            }
        }

    }//GEN-LAST:event_finalizarButtonActionPerformed

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButtonActionPerformed
        

        try {

            int linhaSelecionada = produtosTable.getSelectedRow();
            if (linhaSelecionada < 0) {
                return;
            }

            DefaultTableModel modelo = (DefaultTableModel) produtosTable.getModel();

            String totalString = String.valueOf(modelo.getValueAt(linhaSelecionada, 3));
            totalString = totalString.replace(',', '.').replace("R$", "").trim();
            Double total = Double.parseDouble(totalString);

            String quantidadeString = String.valueOf(modelo.getValueAt(linhaSelecionada, 2));
            Integer quantidade = Integer.parseInt(quantidadeString);

            qtdedeitens -= quantidade;
            qtdeitensLabel.setText("" + qtdedeitens);

            subtotal -= total;
            reaisLabel.setText(String.valueOf(String.format("R$ %.2f", subtotal)));

            modelo.removeRow(linhaSelecionada);

            produtosTable.setFocusable(false);

            novodado();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Não há o que excluir",
                    "Erro",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_xButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:

        if (produtoTextField.getText().isEmpty()) {

            if (beep != null) {
                beep.run();
                JOptionPane.showMessageDialog(null, //NULL
                        "Favor inserir produto", // MENSAGEM
                        "Insira um produto", // TITULO
                        JOptionPane.WARNING_MESSAGE); //ICONE
            }

        } else if (vunitTextField.getText().isEmpty()) {

            if (beep != null) {
                beep.run();

                JOptionPane.showMessageDialog(null, //NULL
                        "Favor inserir Valor Unitário", // MENSAGEM
                        "Valor Unitário", // TITULO
                        JOptionPane.WARNING_MESSAGE); //ICONE
            }

        } else if (qtdeTextField.getText().isEmpty()) {
            if (beep != null) {
                beep.run();
                JOptionPane.showMessageDialog(null, //NULL
                        "Favor inserir Quantidade", // MENSAGEM
                        "Quantidade", // TITULO
                        JOptionPane.WARNING_MESSAGE); //ICONE
            }
        } else {
            String produto = produtoTextField.getText();
            String vunitario = vunitTextField.getText();
            String quantidadeitens = qtdeTextField.getText();

            double vunit = Double.parseDouble(vunitario.replace(",", ".").trim());
            int qtde = Integer.parseInt(quantidadeitens);

            total = vunit * qtde;
            subtotal += total;

            qtdedeitens += qtde;
            qtdeitensLabel.setText("" + qtdedeitens);

            DefaultTableModel modelo = (DefaultTableModel) produtosTable.getModel();

            Object[] linha = {produto, vunit, qtde, total};

            modelo.addRow(linha);

            reaisLabel.setText(String.valueOf(String.format("R$ %.2f", subtotal)));
            novodado();
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void qtdeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdeTextFieldActionPerformed

    private void produtosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_produtosTableMouseClicked

    private void vunitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vunitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vunitTextFieldActionPerformed

    private void vunitTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vunitTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_vunitTextFieldKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        produtoTextField.requestFocus();
        novodado();

        reaisLabel.setText("R$ 0,00");
        qtdeitensLabel.setText("0");
        vunitTextField.setText("");
        trocoTextField.setText("");
        produtoTextField.setText("");
        qtdeTextField.setText("");

    }//GEN-LAST:event_formWindowOpened

    private void produtoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_produtoTextFieldKeyPressed

        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_produtoTextFieldKeyPressed

    private void vunitTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vunitTextFieldKeyPressed
        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_vunitTextFieldKeyPressed

    private void qtdeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtdeTextFieldKeyPressed
        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_qtdeTextFieldKeyPressed

    private void vrecebidoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vrecebidoTextFieldKeyPressed
        
        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            finalizarButton.doClick();
        }
        
    }//GEN-LAST:event_vrecebidoTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupermercadoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupermercadoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupermercadoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupermercadoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupermercadoJFrame().setVisible(true);
            }
        });
    }

    void novodado() {
        produtoTextField.setText("");
        vunitTextField.setText("");
        qtdeTextField.setText("");
        trocoTextField.setText("");
        vrecebidoTextField.setText("");

    }

    private Double total = 0.0;
    private Double subtotal = 0.0;
    private Double troco = 0.0;
    private int qtdedeitens = 0;
    final Runnable beep = (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.exclamation");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton finalizarButton;
    private javax.swing.JLabel itensLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mercadoLabel;
    private javax.swing.JLabel produtoLabel;
    private javax.swing.JTextField produtoTextField;
    private javax.swing.JTable produtosTable;
    private javax.swing.JLabel qtdeLabel;
    private javax.swing.JTextField qtdeTextField;
    private javax.swing.JLabel qtdeitensLabel;
    private javax.swing.JLabel reaisLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel trocoLabel;
    private javax.swing.JTextField trocoTextField;
    private javax.swing.JLabel vrecebidoLabel;
    private javax.swing.JTextField vrecebidoTextField;
    private javax.swing.JTextField vunitTextField;
    private javax.swing.JLabel vunitarioLabel;
    private javax.swing.JButton xButton;
    // End of variables declaration//GEN-END:variables
}
